name = "hex-mod-arith-mathlib"
defaultTargets = ["HexModArithMathlib"]

leanOptions = [
  { name = "doc.verso", value = true },
  { name = "doc.verso.suggestions", value = false },
]

[[require]]
name = "HexModArith"
git = "https://github.com/leanprover/hex-mod-arith.git"
rev = "a73a04b66be68d605a7a92f6cfdcfc6c727fda0f"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.0-rc1"

[[lean_lib]]
name = "HexModArithMathlib"
